spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 21062007
    #username: ${DB_USER}
    #password: ${DB_PASSWORD}
    url: jdbc:postgresql://localhost:5432/chat_app?currentSchema=test_Schema
    #url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}?currentSchema=${DB_SCHEMA}
    hikari:
      schema: ${DB_SCHEMA}
    jpa:
      hibernate:
        ddl-auto: create-drop
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
      database-platform: postgresql
