spring:
  data:
    mongodb:
      username: sickeer
      password: 21062007
      host: localhost
      port: 27017
      database: chat_app
      authentication-database: admin

server:
  port: 8080